POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "The existing code and tests need to be changed when the user is added to the system", 
    "important": true,
    "userId": "60b86ef9387af503a4ac13bc"
}